=== wp-plugins/unicode-character-keyboard/template.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Version 1.0 by Terry O'Brien -->

<!ELEMENT characterSet (
            characterSetFont+, 
            characterSetRange+, 
            characterSetResource, 
            characterSubset+ ) >
<!ATTLIST characterSet          name        CDATA   #REQUIRED >
<!ATTLIST characterSet          description CDATA   #REQUIRED >
<!ATTLIST characterSet          type        CDATA   #REQUIRED >

<!ELEMENT characterSetResource (#PCDATA) >
<!ELEMENT characterSetRange (#PCDATA) >

<!ELEMENT characterSetFont EMPTY >
<!ATTLIST characterSetFont      name        CDATA   #REQUIRED >
<!ATTLIST characterSetFont      url         CDATA   #REQUIRED >

<!ELEMENT characterSubset ( characterSubsetArray+ ) >
<!ATTLIST characterSubset       name        CDATA   #REQUIRED >

<!ELEMENT characterSubsetArray ( characterDefinition+ ) >

<!ELEMENT characterDefinition (#PCDATA) >
<!ATTLIST characterDefinition   character   CDATA   #REQUIRED >

=== wp-plugins/unicode-character-keyboard/template.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Version 1.0 by Terry O'Brien -->

<!DOCTYPE characterSet SYSTEM "template.dtd">

<characterSet name="set name" type="set type" description="set description" >
    <characterSetFont name="" url="" />
    <characterSetRange></characterSetRange>
    <characterSetResource></characterSetResource>

    <characterSetRange></characterSetRange>
    <characterSubset name="subset name 1">
        <characterSubsetArray>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
        </characterSubsetArray>
        <characterSubsetArray>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
        </characterSubsetArray>
    </characterSubset>

    <characterSetRange></characterSetRange>
    <characterSubset name="subset name 2">
        <characterSubsetArray>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
        </characterSubsetArray>
        <characterSubsetArray>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
            <characterDefinition character="character"><!-- character definition --></characterDefinition>
        </characterSubsetArray>
    </characterSubset>
</characterSet>
